fix(ts): `moduleResolution: node12` compat
jakearchibald/idb pull request #265
Opened 2022-05-04 23:30 UTC by aleclarson

TypeScript needs `types` condition when `pkg.exports` is defined 

<img width="503" alt="image" src="https://user-images.githubusercontent.com/1925840/166841471-7006a616-ea0f-4392-b022-ebb363e32485.png">

Source: https://github.com/microsoft/TypeScript/issues/33079#issuecomment-950214842

2022-05-15 11:31 UTC, Loveself7070 requested changes
gh pr checkout 265

2022-06-16 17:16 UTC, JuanM04 commented
Also fixes `"moduleResolution": "node16"` (released in [TypeScript 4.7](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#package-json-exports-imports-and-self-referencing))

2022-06-17 10:38 UTC, jakearchibald commented
Thank you! Sorry it took so long to get round to this.

2022-06-17 10:38 UTC, merged

2022-06-17 13:37 UTC, jakearchibald commented
Published as 7.0.2